image: ocaml/opam:alpine-3.13-ocaml-4.11

stages:
  - build

build:
  stage: build

  artifacts:
    paths:
      - bench-log.txt

  before_script:
    - opam install --yes dune

  script:
    - make all
    - make run | tee bench-log.txt
