image: ocaml/opam:alpine-3.15-ocaml-4.14
# default opam switch name: 4.14

stages:
  - .pre
  - build-4
  - build-5
  - build-crate-4
  - build-crate-5

setup:
  stage: .pre
  script:
    - sudo apk update
    - sudo apk add --no-cache build-base rust cargo ca-certificates
      # opam version: 2.0.10
    - opam repository add beta git+https://github.com/ocaml/ocaml-beta-repository.git
    - opam update
    - opam switch create --yes 5.1.0+trunk --repos beta,default
    - opam install --switch=4.14 --yes dune
    - opam install --switch=5.1.0+trunk --yes dune

build-4:
  stage: build-4
  artifacts:
    paths:
      - bench-log.txt
  before_script:
    - opam switch 4.14
    - eval $(opam env)
  script:
    - make all
    - make run | tee bench-log.txt

build-5:
  stage: build-5
  artifacts:
    paths:
      - bench-log.txt
  before_script:
    - opam switch 5.1.0+trunk
    - eval $(opam env)
  script:
    - make all
    - make run | tee bench-log.txt

build-crate-4:
  stage: build-crate-4
  before_script:
    - opam switch 4.14
    - eval $(opam env)
  script:
    - cd rust/ocaml-boxroot-sys
    - cargo clean
    - cargo build --features "link-ocaml-runtime-and-dummy-program" --verbose
    - cargo test --features "link-ocaml-runtime-and-dummy-program" --verbose

build-crate-5:
  stage: build-crate-5
  before_script:
    - opam switch 5.1.0+trunk
    - eval $(opam env)
  script:
    - cd rust/ocaml-boxroot-sys
    - cargo clean
    - cargo build --features "link-ocaml-runtime-and-dummy-program" --verbose
    - cargo test --features "link-ocaml-runtime-and-dummy-program" --verbose
