image: ocaml/opam:alpine-3.15-ocaml-4.14
# default opam switch name: 4.14

stages:
  - .pre
  - build

setup-5.1:
  stage: .pre
  artifacts:
    paths:
        # Note: once the stable 5.0 is released, this can be converted into a cached dir
      - _opam
  script:
    - export OPAMCLI=2.0
    - opam repository add beta git+https://github.com/ocaml/ocaml-beta-repository.git
    - opam switch create . --packages=ocaml-variants.5.1.0+trunk,dune --repos beta,default --yes
    - opam clean --switch=.

build:
  stage: build
  artifacts:
    paths:
      - bench-log-4.14.txt
      - bench-log-5.1.txt
  before_script:
    - export OPAMCLI=2.0
    - opam install --switch=4.14 --yes dune
  script:
    - echo "Testing Boxroot with OCaml 4.14"
    - ocamlc --version
    - make all
    - make run | tee bench-log-4.14.txt
    - make clean
    - echo "Testing Boxroot with OCaml 5.1"
      # check we have OCaml 5.1.0+trunk
    - opam env --switch=.
      # switch to OCaml 5.1.0+trunk
    - eval $(opam env --switch=. --set-switch)
    - ocamlc --version
    - make all
    - make run | tee bench-log-5.1.txt

build-crate:
  stage: build
  before_script:
    - export OPAMCLI=2.0
    - sudo apk add --no-cache rust cargo ca-certificates
  script:
    - echo "Testing Rust crate with OCaml 4.14"
    - ocamlc --version
    - make test-rs
    - make clean-rs
    - echo "Testing Rust crate with OCaml 5.1"
      # check we have OCaml 5.1.0+trunk
    - opam env --switch=.
      # switch to OCaml 5.1.0+trunk
    - eval $(opam env --switch=. --set-switch)
    - ocamlc --version
    - make test-rs
